# Generated by Django 3.0.6 on 2020-07-25 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='calorie',
        ),
        migrations.RemoveField(
            model_name='food',
            name='colestrol',
        ),
        migrations.RemoveField(
            model_name='food',
            name='fiber',
        ),
        migrations.RemoveField(
            model_name='food',
            name='sugar',
        ),
    ]
