# Generated by Django 3.0.6 on 2020-07-25 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0003_food_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
