# Generated by Django 3.0.6 on 2020-07-25 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0005_auto_20200725_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='category',
        ),
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.ManyToManyField(to='healthapp.Category'),
        ),
    ]
