# Generated by Django 3.0.6 on 2020-07-28 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0007_food_calorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userfood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.ManyToManyField(to='healthapp.food')),
            ],
        ),
    ]
