# Generated by Django 3.0.6 on 2020-07-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0008_userfood'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfood',
            name='customer',
            field=models.ManyToManyField(blank=True, null=True, to='healthapp.Customer'),
        ),
    ]
