# Generated by Django 3.0.6 on 2020-07-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0009_userfood_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfood',
            name='customer',
            field=models.ManyToManyField(blank=True, to='healthapp.Customer'),
        ),
    ]
